name: Push to DigitalOcean App Platform
on:
    push: 
        branches:
            -main
jobs:
    push:
        environment: prod
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: DigitalOcean App Platform deployment
              uses: digitalocean/app_action@v1.1.5  
              with:
                app_name: ${{vars.APP_NAME}}
                token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
            
